//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq_Sorguları_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBSınavEntityEntities : DbContext
    {
        public DBSınavEntityEntities()
            : base("name=DBSınavEntityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblDersler> TblDersler { get; set; }
        public virtual DbSet<TblKulüpler> TblKulüpler { get; set; }
        public virtual DbSet<TblNotlar> TblNotlar { get; set; }
        public virtual DbSet<TblÖğrenci> TblÖğrenci { get; set; }
    
        public virtual ObjectResult<notta_Result> notta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notta_Result>("notta");
        }
    }
}
