//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq_Sorguları_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKulüpler
    {
        public byte KulupID { get; set; }
        public string KulupAd { get; set; }
    }
}
