//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq_Sorguları_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotlar
    {
        public int NotID { get; set; }
        public Nullable<int> Ogr { get; set; }
        public Nullable<int> Ders { get; set; }
        public Nullable<short> Sınav1 { get; set; }
        public Nullable<short> Sınav2 { get; set; }
        public Nullable<short> Sınav3 { get; set; }
        public Nullable<decimal> Ortalama { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TblDersler TblDersler { get; set; }
        public virtual TblÖğrenci TblÖğrenci { get; set; }
    }
}
